GET http://localhost:5298

###
GET http://localhost:5298/games

###
GET http://localhost:5298/games/2

###
POST http://localhost:5298/games
Content-Type: application/json

{
   "name": "Minecraft",
   "genreid": 2,
   "price": 20.00,
   "releaseDate": "2009-05-17"
}

###
PUT http://localhost:5298/games/2
Content-Type: application/json

{
   "name": "Minecraft",
   "genreid": 4,
   "price": 20.00,
   "releaseDate": "2009-05-17"
}

###
DELETE http://localhost:5298/games/5

###
GET http://localhost:5298/genres